#pragma config(Motor, port2, rightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor, port3, Motor2, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port4, Servo_3, tmotorServoStandard, openLoop)
#pragma config(Motor, port5, Servo_4, tmotorServoStandard, openLoop)
#pragma config(Motor, port6, leftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port7, Motor1, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port8, Servo_1, tmotorServoStandard, openLoop)
#pragma config(Motor, port9, Servo_2, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int motor_speed;//for motor_speeds
int servo_speed;//for servo_speeds
bool on_or_off1;// for on/off buttons
bool on_or_off2;// for on/off buttons
bool on_or_off3;// for on/off buttons
bool drive_mode_switch;//drive mode switch
void button_move(int motorvar, int button_variable, int motor_speed
)
{
	motor[motorvar] = vexRT[button_variable] * motor_speed;
}
//^^^turns motor on/off^^^
void button_speed_toggle(int button_variable2, int current_speed, int motor_speed, bool true_or_false, bool true_or_false1)
{
	if (vexRT[button_variable2] == 1 && on_or_off1 == true_or_false)
	{
		motor_speed = current_speed;
		on_or_off1 = true_or_false1;
	}
}
//^^chnages the current_speed of the motors^^
void servo_reverse_toggle(bool true_or_false2, bool true_or_false3)
{
	if (vexRT[Btn8U] == 1 && on_or_off2 == true_or_false2)
	{
		servo_speed = -servo_speed;
		on_or_off2 = true_or_false3;
	}
}
//^^chnages the diretion the servoes goes with a button^^
void modsw(int motor_variable, int motor_variable_2)
//^^Drive Mode switch^^
{
	if (drive_mode_switch == false)
	{
		motor[motor_variable] = vexRT[Ch2];
		motor[motor_variable_2] = vexRT[Ch3];
	}
	//^^tank dive^^
	if (drive_mode_switch == true)
	{
		motor[motor_variable] = vexRT[Ch4] + vexRT[Ch3];
		motor[motor_variable_2] = vexRT[Ch4] - vexRT[Ch3];
	}
}
void button_swtich(bool true_or_false4, bool true_or_false5)
{
	if (vexRT[Btn8D] == 1 && on_or_off3 == true_or_false4)
	{
		servo_speed = -servo_speed;
		on_or_off3 = true_or_false5;
	}
}
// arcarde drive line 53 and 54 code from https://www.vexforum.com/t/robot-c-arcade-drive/43348
// start task main
task main()
{
	on_or_off1 = false;
	on_or_off2 = false;
	on_or_off3 = false;
	// sets the on/off to be false as the defult when the code first runs
	while (true)
	{
		modsw(leftMotor, rightMotor);
		// changes between tank and arcade drive
		servo_reverse_toggle(true, false);
		servo_reverse_toggle(false, true);
		//^^chnages the direction of the servos^^
		button_swtich(true, false);
		button_swtich(false, true);
		// changes between acade and tank drive with a button toggle swtich
		button_speed_toggle(Btn8D, 50, motor_speed, true, false);
		button_speed_toggle(Btn8D, 100, motor_speed, false, true);
		button_speed_toggle(Btn8U, 50, servo_speed, true, false);
		button_speed_toggle(Btn8U, 100, servo_speed, false, true);
		//^^set the motors current_speed with a button^^
		button_move(Motor1, Btn5D, motor_speed);
		button_move(Motor1, Btn6U, -motor_speed);
		button_move(Motor2, Btn5U, motor_speed);
		button_move(Motor2, Btn6U, -motor_speed);
		//^^turns motors on/off^^
		button_move(Servo_1, Btn7R, servo_speed);
		button_move(Servo_2, Btn7L, servo_speed);
		button_move(Servo_3, Btn8R, servo_speed);
		button_move(Servo_4, Btn8L, servo_speed);
		//^^turns servers on/off with a button^^
	}
}
// end task main
// aurth:@coeevee
// date: 9/26/2024
// version: 2.2
// language: RobotC https://www.robotc.net/
// purpose: to control a robot with a controller
// end
